version: '3'
services:
  aeden:
    env_file:
      - ./.env
    image: ${DOCKER_ACCT}/aedan:prfx-${CPU_TYPE}-v${IWC_INTRANET_VERSION}
    build:
      context: ./dns/docker-php-nginx
    deploy:
      mode: replicated
      replicas: 4
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120x
    container_name: aedan
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
    environment:
      - "CERT_DIR=${CERT_DIR}"
      - "NGINX_VERSION=${NGINX_VERSION}"
      - "FFMPEG_VERSION=${FFMPEG_VERSION}"
      - "CFLAGS=${CFLAGS}"
    ports:
      - ${HTTP_ACCESS_PORT}:80
      - ${SSL_ACCESS_PORT}:443
      - ${RTMP_P1}:1935
      - ${PLEX_PORT}:32400
      - ${HTTP_SECONDARY}:8080
    volumes:
      - ./sites:/var/www/html
      - ./ops/certs:/etc/letsencrypt/live
      - ./config/nginx/sites-available:/etc/nginx/sites-available
      - ./config/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config:/intranet/config
      - ./ops/logs:/var/log
      - ./util:/intranet/util
    networks:
      - home
      - ops
    labels:
      com.iwc.stack: "alpine, php, nginx, ffmpg, and rtmp services with support for xdebug, vnc and other passthrough ports"
      com.iwc.description: "Reverse proxy handling of DNS entries"
      com.iwc.type: "proxy"

networks:
  ops:
    driver: bridge
  home:
    driver: bridge
